2022-06-06 17:05:55,454 ERROR: Exception on /user/uxubisg [GET] [in /home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/denis/Dev/checkiner/app/routes.py", line 80, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/denis/Dev/checkiner/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/denis/Dev/checkiner/app/templates/base.html", line 26, in top-level template code
    {% block content %}
  File "/home/denis/Dev/checkiner/app/templates/user.html", line 24, in block 'content'
    {% include 'includes/_post_item.html' %}
  File "/home/denis/Dev/checkiner/app/templates/includes/_post_item.html", line 3, in top-level template code
    <td><img src="{{ post.author.username.avatar(36) }}"></td>
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'avatar'
2022-06-06 17:05:57,655 ERROR: Exception on /user/uxubisg [GET] [in /home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/denis/Dev/checkiner/app/routes.py", line 80, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/denis/Dev/checkiner/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/denis/Dev/checkiner/app/templates/base.html", line 26, in top-level template code
    {% block content %}
  File "/home/denis/Dev/checkiner/app/templates/user.html", line 24, in block 'content'
    {% include 'includes/_post_item.html' %}
  File "/home/denis/Dev/checkiner/app/templates/includes/_post_item.html", line 3, in top-level template code
    <td><img src="{{ post.author.username.avatar(36) }}"></td>
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'avatar'
2022-06-06 17:06:22,104 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:06:51,720 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:07:18,392 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:10:42,255 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:11:05,056 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:14:02,396 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:14:49,240 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:14:59,140 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:15:11,528 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:19:37,856 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:21:26,842 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:22:07,889 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:23:13,048 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:23:47,264 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:24:05,736 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:24:49,628 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:26:13,794 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:27:01,194 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:27:43,483 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:30:00,648 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
2022-06-06 17:30:05,845 ERROR: Exception on /explore [GET] [in /home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/denis/Dev/checkiner/app/routes.py", line 136, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/denis/Dev/checkiner/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/denis/Dev/checkiner/app/templates/base.html", line 26, in top-level template code
    {% block content %}
  File "/home/denis/Dev/checkiner/app/templates/index.html", line 23, in block 'content'
    {% include '_post.html' %}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _post.html
2022-06-06 17:30:17,201 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:46]
