2022-06-07 11:54:53,060 ERROR: Exception on /index [GET] [in /home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/denis/Dev/checkiner/app/routes.py", line 31, in index
    if posts.has_next else None
AttributeError: 'list' object has no attribute 'has_next'
2022-06-07 11:55:18,424 ERROR: Exception on /index [GET] [in /home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/denis/Dev/checkiner/app/routes.py", line 29, in index
    posts = Post.query.all().paginate(
AttributeError: 'list' object has no attribute 'paginate'
2022-06-07 12:09:39,927 ERROR: Exception on /index [GET] [in /home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/denis/Dev/checkiner/app/routes.py", line 29, in index
    posts = Post.query.all().order_by(Post.timestamp.desc()).paginate(
AttributeError: 'list' object has no attribute 'order_by'
2022-06-07 12:31:18,832 ERROR: Exception on /reset_password_request [POST] [in /home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/denis/Dev/checkiner/app/routes.py", line 169, in reset_password_request
    send_password_reset_email(user)
  File "/home/denis/Dev/checkiner/app/email.py", line 18, in send_password_reset_email
    send_email('[Checkiner] Reset Your Password',
TypeError: send_email() missing 1 required positional argument: 'html_body'
2022-06-07 14:49:43,485 ERROR: Exception on /index [GET] [in /home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/denis/Dev/checkiner/app/routes.py", line 25, in index
    posts = current_user.followed_posts().paginate(
AttributeError: 'AnonymousUserMixin' object has no attribute 'followed_posts'
2022-06-07 14:51:17,752 ERROR: Exception on /edit_profile [GET] [in /home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/denis/Dev/checkiner/app/routes.py", line 110, in edit_profile
    return render_template('edit_profile.html', title='Edit Profile',
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/denis/Dev/checkiner/app/templates/edit_profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/denis/Dev/checkiner/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/denis/Dev/checkiner/app/templates/base.html", line 21, in block 'content'
    {% block app_content %} {% endblock %}
  File "/home/denis/Dev/checkiner/app/templates/edit_profile.html", line 7, in block 'app_content'
    {{ wtf.quick_form(form) }}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtf' is undefined
