2022-06-07 11:22:45,121 ERROR: Exception on /reset_password_request [POST] [in /home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/denis/Dev/checkiner/app/routes.py", line 168, in reset_password_request
    send_password_reset_email(user)
  File "/home/denis/Dev/checkiner/app/email.py", line 19, in send_password_reset_email
    text_body=render_template('templates/reset_password.txt',
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1071, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1000, in get_template
    return self._load_template(name, globals)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 959, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: templates/reset_password.txt
2022-06-07 11:25:32,754 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:49]
2022-06-07 11:25:40,145 ERROR: Exception on /reset_password_request [POST] [in /home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/denis/Dev/checkiner/app/routes.py", line 168, in reset_password_request
    send_password_reset_email(user)
  File "/home/denis/Dev/checkiner/app/email.py", line 21, in send_password_reset_email
    html_body=render_template('reset_password_request.html',
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/denis/Dev/checkiner/app/templates/reset_password_request.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/denis/Dev/checkiner/app/templates/base.html", line 26, in top-level template code
    {% block content %}
  File "/home/denis/Dev/checkiner/app/templates/reset_password_request.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-06-07 11:28:36,970 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:49]
2022-06-07 11:28:45,531 ERROR: Exception on /reset_password_request [POST] [in /home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/denis/Dev/checkiner/app/routes.py", line 168, in reset_password_request
    send_password_reset_email(user)
  File "/home/denis/Dev/checkiner/app/email.py", line 21, in send_password_reset_email
    html_body=render_template('reset_password_request.html',
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/denis/Dev/checkiner/app/templates/reset_password_request.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/denis/Dev/checkiner/app/templates/base.html", line 26, in top-level template code
    {% block content %}
  File "/home/denis/Dev/checkiner/app/templates/reset_password_request.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-06-07 11:32:36,582 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:49]
2022-06-07 11:33:16,220 ERROR: Exception on /reset_password_request [POST] [in /home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/denis/Dev/checkiner/app/routes.py", line 168, in reset_password_request
    send_password_reset_email(user)
  File "/home/denis/Dev/checkiner/app/email.py", line 21, in send_password_reset_email
    html_body=render_template('reset_password_request.html',
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/denis/Dev/checkiner/app/templates/reset_password_request.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/denis/Dev/checkiner/app/templates/base.html", line 26, in top-level template code
    {% block content %}
  File "/home/denis/Dev/checkiner/app/templates/reset_password_request.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/denis/Dev/checkiner/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-06-07 11:34:00,606 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:49]
2022-06-07 11:34:25,388 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:49]
2022-06-07 11:35:51,774 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:49]
2022-06-07 11:37:19,929 INFO: Checkiner startup [in /home/denis/Dev/checkiner/app/__init__.py:49]
